### ISSUE TITLE
Add a configuration option to copy the emoji instead of the tag

### ISSUE THREAD

**Issue by GilDev** [Fuhrmann/keypirinha-gitmoji#1]
Thanks for your plugin!
I like to put actual emojis (🎉) in my commit messages instead of the tags (`:tada:`), that way it is more universal to all git platforms (and also works in any modern terminal).
Could it be possible to add a configuration option that allows to choose what is copied in the clipboard?

**Comment by Fuhrmann** [comment]
That would be a nice addition!

**Comment by Fuhrmann** [comment]
```
 {
      "emoji": "🎨",
      "entity": "&#x1f3a8;",
      "code": ":art:",
      "description": "Improving structure / format of the code.",
      "name": "art"
},
```

What do you think, we should copy the `entity` or the `emoji` itself? I'm asking this because I'm having problems with certain emojis in my computer. I don't know if this is related to my virtual machine running Windows.

If I copy the entity and paste it after: `&#x1f3a8;` it turns out &#x1f3a8; in the preview of this comment.

But if I try to copy 🎉 from Keypirinha, I get this after pasting:  �.

**Comment by GilDev** [comment]
That’s weird, don’t have that problem on macOS nor Linux (but I always get less problems with those 😁).
Well I’m not sure what’s best. Does it work if you just copy the entity text and paste it with CTRL+C/CTRL+V or does it paste as text when you do this?

**Comment by Fuhrmann** [comment]
It pastes as text! That's a problem, for sure.

I guess the problem here is Keypirinha, take a look at the image below:

![image](https://user-images.githubusercontent.com/1160365/80042669-029e0680-84d6-11ea-991e-5c5a38f26d4e.png)


As you can see, the `:alien:` emoji renders fine in my browser. But in Keypirinha it renders as a box.

**Comment by Fuhrmann** [comment]
Hey @GilDev check out the new release! If you have any problems let me know!

https://github.com/Fuhrmann/keypirinha-gitmoji/releases/tag/1.1

**Comment by Fuhrmann** [comment]
🎉

**Comment by GilDev** [comment]
> As you can see, the `:alien:` emoji renders fine in my browser. But in Keypirinha it renders as a box.

Yeah Windows seems to handle emojis weirdly depending on the apps, it’s not consistent…
Thank you for the release! Will try when I get the chance to (using Windows at work and of course right now I’m at home)!
